spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssmbuild?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    druid:
      aop-patterns: com.atgui.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）
      stat-view-servlet:   # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false #重置
      web-stat-filter:  # 监控web
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false
#@Value("${person.name:李四}") 可以在类里面拿到配置文件的信息 active: test/prod
  profiles:
    active: prod
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    client-type: LETTUCE

mybatis:
  configuration:
    map-underscore-to-camel-case: true #驼峰命名问题
  config-location: classpath:mybatis/mybatis-config.xml  #全局配置文件位置
#  mapper-locations: classpath:mybatis/mapper/*.xml  #sql映射文件位置

management:
  endpoints:
    enabled-by-default: false #默认开启所有监控端点
    web:
      exposure:
        include: '*' #以web方式暴露所有端点
  endpoint:
    health:
      show-details: always
      enabled: true
    info:
      enabled: true
    beans:
      enabled: true
    metrics:
      enabled: true
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@
  mavenProjectVersion: @project.version@


